import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Users from "../src/v_components/main_components/Users";

const MainApp: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>Main Page</h3>
        <Users />
      </main>
    </div>
  );
};

export default MainApp;
