import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Users from "@/view_components/dashboard/Users";
import Layout from "@/layout";

const Dashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <h3>Main Page</h3>
          <Users />
        </main>
      </Layout>
    </div>
  );
};

export default Dashboard;
