import type { NextPage } from "next";
import Head from "next/head";

import MainForm from "../src/v_components/login_components/MainForm";
import styles from "styles/login.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.login__page}>
        <h2>Login page</h2>
        <MainForm />
      </main>
    </div>
  );
};

export default Home;
