import type { NextPage } from "next";
import Head from "next/head";

import MainForm from "@/view_components/login/MainForm";
import styles from "styles/login.module.scss";
import { useMutation } from "@apollo/client";

const Home: NextPage = () => {
  // const [addTodo] = useMutation(ADD_TODO, {update: updateCache});
  console.log(process.env.API_BASE_URL, "next link");
  return (
    <div className={styles.container}>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.login__page}>
        <h2>Login page</h2>
        <MainForm />
      </main>
    </div>
  );
};

export default Home;
